#debug: true

# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.12:3306/sample?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456

    # 连接池大小根据实际情况调整
    max-active: 100
    max-pool-prepared-statement-per-connection-size: 100

  data:
    # redis配置
    redis:
      database: 0
      host: 192.168.1.12
      port: 10031
      password: 123456
      timeout: 3000

#任务调度中心
xxl:
  job:
    admin:
      accessToken: agx
      addresses: http://192.168.1.12:8081/xxl-job-admin
      timeout: 3
    executor:
      enabled: true
      appName: job-executor-sample-app
      logPath: ./app-log/xxl-job/sample-app
      logRetentionDays: 7
      port: 19091